local two_sum = require('init').two_sum

describe('two_sum', function()
	it('simple', function()
		assert.are.same({ 0, 1 }, two_sum({ 1, 2, 3 }, 3))
	end)
	it('simple reorder', function()
		assert.are.same({ 0, 2 }, two_sum({ 1, 3, 2 }, 3))
	end)
	it('larger numbers', function()
		assert.are.same({ 1, 3 }, two_sum({ 30, 15, 10, 15, 30 }, 30))
	end)
	it('not found', function()
		assert.are.same('not found', two_sum({ 30, 14, 10, 15, 30 }, 30))
	end)
end)
