local two_sum = require('init').two_sum

describe('two_sum', function()
	it('simple', function()
		local indices, err = two_sum({ 1, 2, 3 }, 3)
		assert.are.same({ 0, 1 }, indices)
		assert.is_nil(err)
	end)
	it('simple reorder', function()
		local indices, err = two_sum({ 1, 3, 2 }, 3)
		assert.are.same({ 0, 2 }, indices)
		assert.is_nil(err)
	end)
	it('larger numbers', function()
		local indices, err = two_sum({ 30, 15, 10, 15, 30 }, 30)
		assert.are.same({ 1, 3 }, indices)
		assert.is_nil(err)
	end)
	it('not found', function()
		local indices, err = two_sum({ 30, 14, 10, 15, 30 }, 30)
		assert.is_nil(indices)
		assert.are.same('not found', err)
	end)
end)
